# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule: 
    - cron: "55 23 * * 0"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Calculates traffic and clones and stores in CSV file
    - name: Repository Traffic 
      id: traffic
      uses: sangonzal/repository-traffic-action@0.1.2
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Santiago Gonzalez
        message: "GitHub traffic" 
        add: "./traffic/*"
        ref: "insights"
        
